# Generated by Django 4.2.5 on 2023-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEstudiantesDocentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idEstudiante', models.IntegerField()),
                ('idDocenteMonitor', models.IntegerField()),
                ('idSemestre', models.IntegerField()),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('programa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignaturaCodigo', models.CharField(max_length=50)),
                ('asignaturaNombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=3000)),
                ('periodoPractica', models.CharField(max_length=100)),
                ('aprobacionProg', models.CharField(max_length=100)),
                ('comentariosProg', models.CharField(max_length=100)),
                ('matriculadoAcadFinanc', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('planEstudios', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('inscripcion', models.CharField(max_length=100)),
                ('cursoInduccion', models.CharField(max_length=100)),
                ('rutaPreparacionVl', models.CharField(max_length=100)),
                ('envioHv', models.CharField(max_length=100)),
                ('tituloTecnico', models.CharField(max_length=350)),
                ('practicaDondeLabora', models.CharField(max_length=100)),
                ('estadoUbicacion', models.CharField(max_length=100)),
                ('comentariosProcesoUbicacion', models.CharField(max_length=500)),
                ('tipoContrato', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFinal', models.DateField(auto_now_add=True)),
                ('datosEncargadoProcesoSeleccion', models.CharField(max_length=500)),
                ('datosTutor', models.CharField(max_length=250)),
                ('documentosPendientes', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('semestreRegistro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('correoPersonal', models.EmailField(max_length=254)),
                ('correoInstitucional', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('programa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocenteMonitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idPrograma', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('correoPersonal', models.EmailField(max_length=254)),
                ('correoInstitucional', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('horasDisponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('emailInstitucional', models.CharField(max_length=100)),
                ('emailPersonal', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('semestre', models.CharField(max_length=10)),
                ('certificadoArl', models.CharField(max_length=500)),
                ('certificadoEps', models.CharField(max_length=500)),
                ('contratoPractica', models.CharField(max_length=500)),
                ('idDocenteMonitor', models.IntegerField(default=0)),
                ('idAsignatura', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('programaNombre', models.CharField(max_length=50)),
                ('programaCodigo', models.CharField(max_length=50)),
                ('idCoordinador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('numeroSemestre', models.CharField(max_length=20)),
            ],
        ),
    ]
