# Generated by Django 4.2.5 on 2023-09-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantesDoc2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=3000)),
                ('periodoPractica', models.CharField(max_length=100)),
                ('aprobacionProg', models.CharField(max_length=100)),
                ('comentariosProg', models.CharField(max_length=100)),
                ('matriculadoAcadFinanc', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('planEstudios', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('inscripcion', models.CharField(max_length=100)),
                ('cursoInduccion', models.CharField(max_length=100)),
                ('rutaPreparacionVl', models.CharField(max_length=100)),
                ('envioHv', models.CharField(max_length=100)),
                ('tituloTecnico', models.CharField(max_length=350)),
                ('practicaDondeLabora', models.CharField(max_length=100)),
                ('estadoUbicacion', models.CharField(max_length=100)),
                ('comentariosProcesoUbicacion', models.CharField(max_length=500)),
                ('tipoContrato', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFinal', models.DateField(auto_now_add=True)),
                ('datosEncargadoProcesoSeleccion', models.CharField(max_length=500)),
                ('datosTutor', models.CharField(max_length=250)),
                ('documentosPendientes', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('semestreRegistro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('emailInstitucional', models.CharField(max_length=100)),
                ('emailPersonal', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('semestre', models.CharField(max_length=10)),
            ],
        ),
    ]
