# Generated by Django 4.2.5 on 2023-10-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followPractApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('numeroSemestre', models.CharField(max_length=20)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
